name: CSU-Library-Reserve-Gf

on:
  workflow_dispatch:
 
  schedule:
    - cron: '06 05 * * *'
  
jobs:
  reserve:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Reserve
      run: |
        user='${{ secrets.USER_GF }}'
        pwd='${{ secrets.PWD_GF }}'
        python3 helper.py --userid $user --password $pwd
     
